/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NIMGraphManager
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");

// nim-service.ts
var NIMService = class {
  constructor(config, retryConfig = {
    maxRetries: 3,
    initialDelay: 1e3,
    maxDelay: 1e4,
    backoffMultiplier: 2
  }) {
    this.config = config;
    this.retryConfig = retryConfig;
  }
  async fetchWithRetry(url, options, attemptNumber = 0) {
    try {
      const response = await fetch(url, {
        ...options,
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.config.apiKey}`,
          ...options.headers
        }
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP ${response.status}: ${errorText}`);
      }
      return await response.json();
    } catch (error) {
      if (attemptNumber >= this.retryConfig.maxRetries) {
        throw new Error(`Request failed after ${this.retryConfig.maxRetries} retries: ${error instanceof Error ? error.message : String(error)}`);
      }
      const delay = Math.min(
        this.retryConfig.initialDelay * Math.pow(this.retryConfig.backoffMultiplier, attemptNumber),
        this.retryConfig.maxDelay
      );
      await this.sleep(delay);
      return this.fetchWithRetry(url, options, attemptNumber + 1);
    }
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  buildApiUrl(path) {
    let endpoint = this.config.endpoint;
    if (!endpoint || endpoint.trim() === "") {
      throw new Error("API endpoint is not configured");
    }
    endpoint = endpoint.trim();
    if (endpoint.endsWith("/")) {
      endpoint = endpoint.slice(0, -1);
    }
    if (endpoint.endsWith("/v1")) {
      return `${endpoint}${path}`;
    }
    if (path.startsWith("/")) {
      return `${endpoint}/v1${path}`;
    }
    return `${endpoint}/v1/${path}`;
  }
  async getEmbedding(text) {
    const request = {
      input: text,
      model: this.config.embeddingModel,
      encoding_format: "float"
    };
    const apiUrl = this.buildApiUrl("/embeddings");
    const response = await this.fetchWithRetry(
      apiUrl,
      {
        method: "POST",
        body: JSON.stringify(request)
      }
    );
    if (response.data.length === 0) {
      throw new Error("No embedding data returned from API");
    }
    return response.data[0].embedding;
  }
  async getBatchEmbeddings(texts) {
    const batchSize = 20;
    const embeddings = [];
    for (let i = 0; i < texts.length; i += batchSize) {
      const batch = texts.slice(i, i + batchSize);
      const request = {
        input: batch,
        model: this.config.embeddingModel,
        encoding_format: "float"
      };
      const apiUrl = this.buildApiUrl("/embeddings");
      const response = await this.fetchWithRetry(
        apiUrl,
        {
          method: "POST",
          body: JSON.stringify(request)
        }
      );
      for (const data of response.data) {
        embeddings[data.index + i / batchSize * batchSize] = data.embedding;
      }
    }
    return embeddings;
  }
  async extractNoteEmbedding(note) {
    const content = this.prepareNoteContent(note);
    const embedding = await this.getEmbedding(content);
    return { noteId: note.id, embedding };
  }
  async extractNoteEmbeddingsBatch(notes) {
    const texts = notes.map((note) => this.prepareNoteContent(note));
    const embeddings = await this.getBatchEmbeddings(texts);
    const embeddingMap = /* @__PURE__ */ new Map();
    notes.forEach((note, index) => {
      embeddingMap.set(note.id, embeddings[index]);
    });
    return embeddingMap;
  }
  prepareNoteContent(note) {
    let content = note.title;
    if (note.content) {
      content += "\n\n" + note.content;
    }
    if (note.metadata) {
      const metadataContent = Object.entries(note.metadata).filter(([key]) => key !== "position").map(([key, value]) => `${key}: ${JSON.stringify(value)}`).join("\n");
      if (metadataContent) {
        content += "\n\n" + metadataContent;
      }
    }
    return content;
  }
  cosineSimilarity(a, b) {
    if (a.length !== b.length) {
      throw new Error("Vector dimensions must match");
    }
    let dotProduct = 0;
    let normA = 0;
    let normB = 0;
    for (let i = 0; i < a.length; i++) {
      dotProduct += a[i] * b[i];
      normA += a[i] * a[i];
      normB += b[i] * b[i];
    }
    return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
  }
  async calculateSimilarity(note1, note2, embeddings) {
    let embedding1, embedding2;
    if (embeddings) {
      embedding1 = embeddings.get(note1.id);
      embedding2 = embeddings.get(note2.id);
    }
    if (!embedding1) {
      embedding1 = await this.getEmbedding(this.prepareNoteContent(note1));
    }
    if (!embedding2) {
      embedding2 = await this.getEmbedding(this.prepareNoteContent(note2));
    }
    return this.cosineSimilarity(embedding1, embedding2);
  }
  async findSimilarNotes(targetNote, candidateNotes, threshold = 0.5, embeddings) {
    const results = [];
    if (!embeddings) {
      embeddings = await this.extractNoteEmbeddingsBatch([targetNote, ...candidateNotes]);
    }
    const targetEmbedding = embeddings.get(targetNote.id);
    if (!targetEmbedding) {
      throw new Error("Target note embedding not found");
    }
    for (const candidate of candidateNotes) {
      const candidateEmbedding = embeddings.get(candidate.id);
      if (!candidateEmbedding) {
        continue;
      }
      const similarity = this.cosineSimilarity(targetEmbedding, candidateEmbedding);
      if (similarity >= threshold) {
        results.push({
          noteId: candidate.id,
          score: similarity
        });
      }
    }
    return results.sort((a, b) => b.score - a.score);
  }
  async suggestConnectionsBatch(notes, threshold = 0.6, maxConnections = 5) {
    const embeddings = await this.extractNoteEmbeddingsBatch(notes);
    const suggestions = [];
    for (let i = 0; i < notes.length; i++) {
      const sourceEmbedding = embeddings.get(notes[i].id);
      if (!sourceEmbedding)
        continue;
      const similarities = [];
      for (let j = 0; j < notes.length; j++) {
        if (i === j)
          continue;
        const targetEmbedding = embeddings.get(notes[j].id);
        if (!targetEmbedding)
          continue;
        const similarity = this.cosineSimilarity(sourceEmbedding, targetEmbedding);
        if (similarity >= threshold) {
          similarities.push({ index: j, score: similarity });
        }
      }
      similarities.sort((a, b) => b.score - a.score);
      for (let k = 0; k < Math.min(similarities.length, maxConnections); k++) {
        const targetIndex = similarities[k].index;
        suggestions.push({
          sourceId: notes[i].id,
          targetId: notes[targetIndex].id,
          score: similarities[k].score,
          reason: "semantic_similarity"
        });
      }
    }
    return suggestions;
  }
  async generateConnectionExplanation(note1, note2, similarity) {
    const request = {
      model: this.config.chatModel,
      messages: [
        {
          role: "system",
          content: "You are a helpful assistant that explains relationships between notes. Provide a concise one-sentence explanation."
        },
        {
          role: "user",
          content: `Explain why these two notes are connected with a similarity score of ${similarity.toFixed(2)}: Note 1: "${note1.title} - ${note1.content.substring(0, 200)}..." Note 2: "${note2.title} - ${note2.content.substring(0, 200)}..."`
        }
      ],
      temperature: 0.7,
      max_tokens: 150
    };
    const apiUrl = this.buildApiUrl("/chat/completions");
    const response = await this.fetchWithRetry(
      apiUrl,
      {
        method: "POST",
        body: JSON.stringify(request)
      }
    );
    if (response.choices.length === 0) {
      throw new Error("No completion choices returned from API");
    }
    return response.choices[0].message.content.trim();
  }
  async processBatchWithRetry(batch, processor) {
    const batchSize = batch.batchSize || 10;
    const results = [];
    for (let i = 0; i < batch.items.length; i += batchSize) {
      const chunk = batch.items.slice(i, i + batchSize);
      const chunkResults = await processor(chunk);
      results.push(...chunkResults);
    }
    return results;
  }
  async healthCheck() {
    try {
      try {
        const apiUrl = this.buildApiUrl("/embeddings");
        await this.fetchWithRetry(
          apiUrl,
          {
            method: "POST",
            body: JSON.stringify({
              input: "test",
              model: this.config.embeddingModel,
              encoding_format: "float"
            })
          }
        );
        return true;
      } catch (error) {
        console.log("Health check via embedding endpoint failed, trying chat endpoint:", error);
      }
      const chatUrl = this.buildApiUrl("/chat/completions");
      await this.fetchWithRetry(
        chatUrl,
        {
          method: "POST",
          body: JSON.stringify({
            model: this.config.chatModel,
            messages: [{ role: "user", content: "test" }],
            max_tokens: 1
          })
        }
      );
      return true;
    } catch (error) {
      console.error("Health check failed:", error);
      return false;
    }
  }
  async getAvailableModels() {
    const apiUrl = this.buildApiUrl("/models");
    return this.fetchWithRetry(
      apiUrl,
      { method: "GET" }
    );
  }
  updateConfig(partialConfig) {
    this.config = { ...this.config, ...partialConfig };
  }
  updateRetryConfig(partialConfig) {
    this.retryConfig = { ...this.retryConfig, ...partialConfig };
  }
  getConfig() {
    return { ...this.config };
  }
  getRetryConfig() {
    return { ...this.retryConfig };
  }
};

// settings.ts
var DEFAULT_SETTINGS = {
  endpoint: "https://integrate.api.nvidia.com/v1",
  apiKey: "",
  embeddingModel: "nvidia/nv-embedqa-e5-v5",
  chatModel: "nvidia/llama-3.1-nemotron-70b-instruct",
  connectionThreshold: 0.6,
  autoProcessOnLoad: false,
  autoProcessThreshold: 0.7,
  maxSuggestedConnections: 5,
  showNotifications: true
};
var NIMGraphSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.nimService = null;
    this.plugin = plugin;
    this.settings = plugin.settings;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "NVIDIA NIM Graph Manager Settings" });
    new import_obsidian.Setting(containerEl).setName("API Endpoint").setDesc("The base URL of your API provider (e.g., https://integrate.api.nvidia.com/v1 or https://api.openai.com/v1). The plugin will automatically handle the API paths.").addText((text) => {
      text.setPlaceholder("https://integrate.api.nvidia.com/v1").setValue(this.settings.endpoint).onChange(async (value) => {
        this.settings.endpoint = value.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "url";
    });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Your NVIDIA NIM API key (will be stored securely)").addText((text) => {
      text.setPlaceholder("Enter your API key").setValue(this.settings.apiKey).onChange(async (value) => {
        this.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    this.createModelSettings(containerEl);
    this.createConnectionSettings(containerEl);
    this.createAutoProcessingSettings(containerEl);
    this.createTestSettings(containerEl);
  }
  createModelSettings(containerEl) {
    const modelSection = containerEl.createEl("div", { cls: "setting-item" });
    modelSection.createEl("h3", { text: "Model Configuration" });
    new import_obsidian.Setting(containerEl).setName("Embedding Model").setDesc("The model to use for generating text embeddings").addDropdown((dropdown) => {
      const embeddingModels = [
        "nvidia/nv-embedqa-e5-v5",
        "nvidia/nv-embedqa-mistral-7b-v2",
        "nvidia/nv-embedqa-001",
        "openai/text-embedding-ada-002"
      ];
      embeddingModels.forEach((model) => {
        dropdown.addOption(model, model.split("/").pop() || model);
      });
      dropdown.setValue(this.settings.embeddingModel);
      dropdown.onChange(async (value) => {
        this.settings.embeddingModel = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Chat Model").setDesc("The model to use for generating connection explanations").addDropdown((dropdown) => {
      const chatModels = [
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "nvidia/llama-3.1-8b-instruct",
        "nvidia/llama-3-70b-instruct",
        "nvidia/llama-3-8b-instruct",
        "meta/llama-3.1-405b-instruct"
      ];
      chatModels.forEach((model) => {
        dropdown.addOption(model, model.split("/").pop() || model);
      });
      dropdown.setValue(this.settings.chatModel);
      dropdown.onChange(async (value) => {
        this.settings.chatModel = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Refresh Available Models").setDesc("Fetch and update the list of available models from the API").addButton((button) => {
      button.setButtonText("Refresh Models");
      button.onClick(async () => {
        var _a;
        button.setButtonText("Loading...");
        button.setDisabled(true);
        try {
          const service = this.createNIMService();
          const models = await service.getAvailableModels();
          const noticeEl = containerEl.createEl("div", {
            cls: "setting-item-description",
            text: `Found ${((_a = models.data) == null ? void 0 : _a.length) || 0} available models`
          });
          setTimeout(() => noticeEl.remove(), 5e3);
        } catch (error) {
          const errorEl = containerEl.createEl("div", {
            cls: "setting-item-description mod-error",
            text: `Failed to fetch models: ${error instanceof Error ? error.message : "Unknown error"}`
          });
          setTimeout(() => errorEl.remove(), 5e3);
        }
        button.setButtonText("Refresh Models");
        button.setDisabled(false);
      });
    });
  }
  createConnectionSettings(containerEl) {
    const connectionSection = containerEl.createEl("div", { cls: "setting-item" });
    connectionSection.createEl("h3", { text: "Connection Settings" });
    new import_obsidian.Setting(containerEl).setName("Connection Threshold").setDesc("Minimum similarity score required for suggesting a connection (0.0 - 1.0)").addText((text) => {
      text.setPlaceholder("0.6").setValue(this.settings.connectionThreshold.toString()).onChange(async (value) => {
        const numValue = parseFloat(value);
        if (!isNaN(numValue) && numValue >= 0 && numValue <= 1) {
          this.settings.connectionThreshold = numValue;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "1";
      text.inputEl.step = "0.1";
    });
    new import_obsidian.Setting(containerEl).setName("Max Suggested Connections").setDesc("Maximum number of connections to suggest per note").addText((text) => {
      text.setPlaceholder("5").setValue(this.settings.maxSuggestedConnections.toString()).onChange(async (value) => {
        const numValue = parseInt(value);
        if (!isNaN(numValue) && numValue > 0) {
          this.settings.maxSuggestedConnections = numValue;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.min = "1";
      text.inputEl.max = "50";
      text.inputEl.step = "1";
    });
  }
  createAutoProcessingSettings(containerEl) {
    const autoSection = containerEl.createEl("div", { cls: "setting-item" });
    autoSection.createEl("h3", { text: "Automatic Processing" });
    new import_obsidian.Setting(containerEl).setName("Auto Process on Load").setDesc("Automatically analyze graph connections when Obsidian loads").addToggle((toggle) => {
      toggle.setValue(this.settings.autoProcessOnLoad).onChange(async (value) => {
        this.settings.autoProcessOnLoad = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Auto Process Threshold").setDesc("Connection threshold used during automatic processing").addText((text) => {
      text.setPlaceholder("0.7").setValue(this.settings.autoProcessThreshold.toString()).onChange(async (value) => {
        const numValue = parseFloat(value);
        if (!isNaN(numValue) && numValue >= 0 && numValue <= 1) {
          this.settings.autoProcessThreshold = numValue;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "1";
      text.inputEl.step = "0.1";
    });
    new import_obsidian.Setting(containerEl).setName("Show Notifications").setDesc("Display notifications when connections are found").addToggle((toggle) => {
      toggle.setValue(this.settings.showNotifications).onChange(async (value) => {
        this.settings.showNotifications = value;
        await this.plugin.saveSettings();
      });
    });
  }
  createTestSettings(containerEl) {
    const testSection = containerEl.createEl("div", { cls: "setting-item" });
    testSection.createEl("h3", { text: "Test Connection" });
    const testButtonContainer = new import_obsidian.Setting(containerEl).setName("Test API Connection").setDesc("Verify your API configuration is working correctly").addButton((button) => {
      button.setButtonText("Test Connection");
      button.setClass("mod-cta");
      button.buttonEl.addEventListener("click", async () => {
        const buttonEl = button.buttonEl;
        const originalText = buttonEl.textContent;
        buttonEl.textContent = "Testing...";
        buttonEl.disabled = true;
        try {
          if (!this.settings.endpoint) {
            this.showErrorMessage(containerEl, "Please enter an API endpoint first.");
            buttonEl.textContent = originalText;
            buttonEl.disabled = false;
            return;
          }
          if (!this.settings.apiKey) {
            this.showErrorMessage(containerEl, "Please enter an API key first.");
            buttonEl.textContent = originalText;
            buttonEl.disabled = false;
            return;
          }
          const service = this.createNIMService();
          const isHealthy = await service.healthCheck();
          if (isHealthy) {
            this.showSuccessMessage(containerEl, "Connection successful! Your API configuration is working.");
          } else {
            this.showErrorMessage(containerEl, "Connection failed. Please check your API endpoint and key, and verify your internet connection.");
          }
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : "Unknown error";
          console.error("API connection test failed:", error);
          this.showErrorMessage(containerEl, `Connection error: ${errorMsg}. Please check your endpoint format and API key.`);
        }
        buttonEl.textContent = originalText;
        buttonEl.disabled = false;
      });
    });
    new import_obsidian.Setting(containerEl).setName("Validate Configuration").setDesc("Check if all required fields are configured").addButton((button) => {
      button.setButtonText("Validate");
      button.buttonEl.addEventListener("click", () => {
        const issues = [];
        if (!this.settings.endpoint) {
          issues.push("API endpoint is required");
        }
        if (!this.settings.apiKey) {
          issues.push("API key is required");
        }
        if (!this.settings.embeddingModel) {
          issues.push("Embedding model must be selected");
        }
        if (!this.settings.chatModel) {
          issues.push("Chat model must be selected");
        }
        if (this.settings.connectionThreshold < 0 || this.settings.connectionThreshold > 1) {
          issues.push("Connection threshold must be between 0 and 1");
        }
        if (this.settings.autoProcessThreshold < 0 || this.settings.autoProcessThreshold > 1) {
          issues.push("Auto process threshold must be between 0 and 1");
        }
        if (this.settings.maxSuggestedConnections < 1) {
          issues.push("Max suggested connections must be at least 1");
        }
        if (issues.length === 0) {
          this.showSuccessMessage(containerEl, "All configuration is valid!");
        } else {
          this.showErrorMessage(containerEl, issues.join(". "));
        }
      });
    });
  }
  createNIMService() {
    return new NIMService({
      apiKey: this.settings.apiKey,
      endpoint: this.settings.endpoint,
      embeddingModel: this.settings.embeddingModel,
      chatModel: this.settings.chatModel
    });
  }
  showSuccessMessage(containerEl, message) {
    const successEl = containerEl.createEl("div", {
      cls: "setting-item-description mod-success",
      text: `\u2713 ${message}`
    });
    setTimeout(() => successEl.remove(), 5e3);
  }
  showErrorMessage(containerEl, message) {
    const errorEl = containerEl.createEl("div", {
      cls: "setting-item-description mod-error",
      text: `\u2717 ${message}`
    });
    setTimeout(() => errorEl.remove(), 5e3);
  }
  updateSettings(newSettings) {
    this.settings = { ...this.settings, ...newSettings };
  }
  getSettings() {
    return { ...this.settings };
  }
};

// main.ts
var NIMGraphManager = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.noteMetadata = /* @__PURE__ */ new Map();
    this.potentialConnections = [];
    this.nimService = new NIMService({
      endpoint: this.settings.endpoint,
      apiKey: this.settings.apiKey,
      embeddingModel: this.settings.embeddingModel,
      chatModel: this.settings.chatModel
    });
    this.addRibbonIcon("network", "NIM Graph Manager", () => {
      this.analyzeAndSuggestConnections();
    });
    this.addCommand({
      id: "analyze-graph",
      name: "Analyze notes and suggest connections",
      callback: () => {
        this.analyzeAndSuggestConnections();
      }
    });
    this.addCommand({
      id: "open-nim-settings",
      name: "Open NIM Graph settings",
      callback: () => {
        this.app.setting.open();
        this.app.setting.openTabById("nim-graph-manager");
      }
    });
    this.addSettingTab(new NIMGraphSettingsTab(this.app, this));
    if (this.settings.autoProcessOnLoad) {
      this.analyzeAndSuggestConnections();
    }
    console.log("NIM Graph Manager plugin loaded");
  }
  onunload() {
    console.log("NIM Graph Manager plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.settings && this.nimService) {
      this.nimService.updateConfig({
        endpoint: this.settings.endpoint,
        apiKey: this.settings.apiKey,
        embeddingModel: this.settings.embeddingModel,
        chatModel: this.settings.chatModel
      });
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async analyzeAndSuggestConnections() {
    if (!this.settings.endpoint || !this.settings.apiKey) {
      new import_obsidian2.Notice("Please configure your NVIDIA NIM API settings first");
      return;
    }
    new import_obsidian2.Notice("Analyzing notes...");
    await this.collectNoteMetadata();
    this.potentialConnections = await this.generatePotentialConnections();
    this.displayConnectionSuggestions();
  }
  async collectNoteMetadata() {
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const metadata = await this.extractNoteMetadata(file);
      this.noteMetadata.set(file.path, metadata);
    }
  }
  async extractNoteMetadata(file) {
    const content = await this.app.vault.read(file);
    const cache = this.app.metadataCache.getFileCache(file);
    const tags = /* @__PURE__ */ new Set();
    const links = [];
    const frontmatter = {};
    if (cache == null ? void 0 : cache.tags) {
      cache.tags.forEach((tag) => tags.add(tag.tag.replace(/^#/, "")));
    }
    if (cache == null ? void 0 : cache.links) {
      cache.links.forEach((link) => links.push(link.link));
    }
    if (cache == null ? void 0 : cache.frontmatter) {
      Object.assign(frontmatter, cache.frontmatter);
    }
    const title = frontmatter.title || file.basename;
    return {
      path: file.path,
      title,
      content,
      tags: [...tags],
      links,
      frontmatter
    };
  }
  async generatePotentialConnections() {
    const connections = [];
    const entries = Array.from(this.noteMetadata.entries());
    for (let i = 0; i < entries.length; i++) {
      for (let j = i + 1; j < entries.length; j++) {
        const [pathA, metaA] = entries[i];
        const [pathB, metaB] = entries[j];
        const connection = await this.analyzeConnection(metaA, metaB);
        if (connection && connection.confidence > 0.5) {
          connections.push(connection);
        }
      }
    }
    return connections.sort((a, b) => b.confidence - a.confidence);
  }
  async analyzeConnection(metaA, metaB) {
    const sharedTags = metaA.tags.filter((tag) => metaB.tags.includes(tag));
    const hasExistingLink = metaA.links.includes(metaB.title) || metaB.links.includes(metaA.title);
    if (hasExistingLink) {
      return null;
    }
    let confidence = 0;
    let reasons = [];
    if (sharedTags.length > 0) {
      confidence += 0.3 * sharedTags.length;
      reasons.push(`Shared tags: ${sharedTags.join(", ")}`);
    }
    const termOverlap = this.calculateTermOverlap(metaA, metaB);
    if (termOverlap > 0.2) {
      confidence += 0.3;
      reasons.push(`High term overlap: ${(termOverlap * 100).toFixed(0)}%`);
    }
    if (this.settings.apiKey && this.settings.endpoint) {
      try {
        const aiReasoning = await this.getAIConnectionSuggestion(metaA, metaB);
        if (aiReasoning.suggested) {
          confidence += aiReasoning.confidence;
          reasons.push(aiReasoning.reason);
        }
      } catch (error) {
        console.error("AI suggestion failed:", error);
      }
    }
    if (confidence === 0) {
      return null;
    }
    return {
      sourceNote: metaA.path,
      targetNote: metaB.path,
      weight: confidence,
      reason: reasons.join("; "),
      confidence: Math.min(confidence, 1)
    };
  }
  calculateTermOverlap(metaA, metaB) {
    const extractTerms = (content) => {
      const words = content.toLowerCase().replace(/[^\w\s]/g, "").split(/\s+/).filter((word) => word.length > 3);
      return new Set(words);
    };
    const termsA = extractTerms(metaA.content);
    const termsB = extractTerms(metaB.content);
    const intersection = new Set([...termsA].filter((x) => termsB.has(x)));
    const union = /* @__PURE__ */ new Set([...termsA, ...termsB]);
    return union.size > 0 ? intersection.size / union.size : 0;
  }
  async getAIConnectionSuggestion(metaA, metaB) {
    try {
      const note1 = { id: metaA.path, title: metaA.title, content: metaA.content };
      const note2 = { id: metaB.path, title: metaB.title, content: metaB.content };
      const similarity = this.calculateTermOverlap(metaA, metaB);
      const explanation = await this.nimService.generateConnectionExplanation(
        note1,
        note2,
        similarity
      );
      return {
        suggested: true,
        confidence: similarity * 0.4,
        reason: explanation
      };
    } catch (error) {
      console.error("AI suggestion failed:", error);
      return {
        suggested: false,
        confidence: 0,
        reason: ""
      };
    }
  }
  displayConnectionSuggestions() {
    if (this.potentialConnections.length === 0) {
      new import_obsidian2.Notice("No significant connections found");
      return;
    }
    const message = `Found ${this.potentialConnections.length} potential connections. Check console for details.`;
    new import_obsidian2.Notice(message);
    console.log("Potential connections:", this.potentialConnections);
  }
};
